//go:build ignore

// update.go refreshes the Swagger UI files embedded in package swagger and
// the pinned CDN versions and Subresource Integrity hashes in ../pins.go.
// Run it from the repository root:
//
//	go run ./middleware/swagger/assets/update.go -swagger-ui 5.33.1 -scalar 1.72.4 -redoc 2.5.4
//
// For each package it downloads the npm tarball of the exact version,
// refuses it unless it matches the registry's sha512 integrity, and hashes
// the files the pages load (sha384, the SRI form browsers check). The
// Swagger UI files and their licence notices are copied into
// assets/swagger-ui-dist/, replacing the old copy. The files are written
// byte for byte as published, so the embedded copy and the pinned CDN copy
// have the same hash. Review the diff of pins.go before committing.
package main

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"crypto/sha512"
	"encoding/base64"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

const (
	assetsDir = "middleware/swagger/assets/swagger-ui-dist"
	pinsFile  = "middleware/swagger/pins.go"
	registry  = "https://registry.npmjs.org"
)

// swaggerUIFiles are copied from the swagger-ui-dist tarball into
// assetsDir: the three files the page loads and the licence notices
// (Apache-2.0 LICENSE and NOTICE, and the bundles' third-party notices).
var swaggerUIFiles = []string{
	"swagger-ui.css",
	"swagger-ui-bundle.js",
	"swagger-ui-standalone-preset.js",
	"swagger-ui-bundle.js.LICENSE.txt",
	"swagger-ui-standalone-preset.js.LICENSE.txt",
	"LICENSE",
	"NOTICE",
}

var client = &http.Client{Timeout: 3 * time.Minute}

var semver = regexp.MustCompile(`^[0-9]+\.[0-9]+\.[0-9]+$`)

func main() {
	swaggerUI := flag.String("swagger-ui", "", "exact swagger-ui-dist version")
	scalar := flag.String("scalar", "", "exact @scalar/api-reference version")
	redoc := flag.String("redoc", "", "exact redoc version")
	flag.Parse()
	for _, v := range []string{*swaggerUI, *scalar, *redoc} {
		if !semver.MatchString(v) {
			log.Fatalf("every version must be an exact x.y.z release, got %q", v)
		}
	}
	if _, err := os.Stat("middleware/swagger/swagger.go"); err != nil {
		log.Fatalf("run from the repository root: %v", err)
	}

	sw := fetch("swagger-ui-dist", *swaggerUI)
	sc := fetch("@scalar/api-reference", *scalar)
	rd := fetch("redoc", *redoc)

	if err := os.RemoveAll(assetsDir); err != nil {
		log.Fatal(err)
	}
	if err := os.MkdirAll(assetsDir, 0o755); err != nil {
		log.Fatal(err)
	}
	for _, name := range swaggerUIFiles {
		if err := os.WriteFile(filepath.Join(assetsDir, name), sw.file(name), 0o644); err != nil {
			log.Fatal(err)
		}
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, `// Code generated by assets/update.go; DO NOT EDIT.

package swagger

// The exact upstream versions this release is pinned to. Swagger UI is
// embedded at SwaggerUIVersion and served by default; with Config.CDN the
// pages load each renderer from jsDelivr at these versions.
const (
	// SwaggerUIVersion is the embedded and CDN swagger-ui-dist version.
	SwaggerUIVersion = %q
	// ScalarVersion is the CDN @scalar/api-reference version.
	ScalarVersion = %q
	// ReDocVersion is the CDN redoc version.
	ReDocVersion = %q
)

// Subresource Integrity values (sha384) of the files the pages load.
// Sources (npm tarball, registry integrity):
//   %s %s
//   %s %s
//   %s %s
const (
	sriSwaggerUICSS    = %q
	sriSwaggerUIBundle = %q
	sriSwaggerUIPreset = %q
	sriScalar          = %q
	sriReDoc           = %q
)
`,
		*swaggerUI, *scalar, *redoc,
		sw.tarball, sw.integrity, sc.tarball, sc.integrity, rd.tarball, rd.integrity,
		sri(sw.file("swagger-ui.css")), sri(sw.file("swagger-ui-bundle.js")),
		sri(sw.file("swagger-ui-standalone-preset.js")),
		sri(sc.file("dist/browser/standalone.js")), sri(rd.file("bundles/redoc.standalone.js")))
	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(pinsFile, src, 0o644); err != nil {
		log.Fatal(err)
	}
	log.Printf("wrote %s and %d files in %s", pinsFile, len(swaggerUIFiles), assetsDir)
}

type pkg struct {
	tarball, integrity string
	files              map[string][]byte // path inside "package/"
}

func (p pkg) file(name string) []byte {
	b, ok := p.files[name]
	if !ok {
		log.Fatalf("%s has no file %q", p.tarball, name)
	}
	return b
}

func get(url string) []byte {
	resp, err := client.Get(url)
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		log.Fatalf("GET %s: %s", url, resp.Status)
	}
	b, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Fatal(err)
	}
	return b
}

// fetch downloads name@version, verifies the tarball against the
// registry's sha512 integrity and returns its regular files.
func fetch(name, version string) pkg {
	var meta struct {
		Dist struct {
			Tarball   string `json:"tarball"`
			Integrity string `json:"integrity"`
		} `json:"dist"`
	}
	if err := json.Unmarshal(get(registry+"/"+name+"/"+version), &meta); err != nil {
		log.Fatalf("%s@%s metadata: %v", name, version, err)
	}
	if !strings.HasPrefix(meta.Dist.Integrity, "sha512-") {
		log.Fatalf("%s@%s: registry integrity %q is not sha512", name, version, meta.Dist.Integrity)
	}
	tgz := get(meta.Dist.Tarball)
	sum := sha512.Sum512(tgz)
	if got := "sha512-" + base64.StdEncoding.EncodeToString(sum[:]); got != meta.Dist.Integrity {
		log.Fatalf("%s: tarball %s does not match the registry integrity %s", meta.Dist.Tarball, got, meta.Dist.Integrity)
	}
	zr, err := gzip.NewReader(bytes.NewReader(tgz))
	if err != nil {
		log.Fatal(err)
	}
	p := pkg{tarball: meta.Dist.Tarball, integrity: meta.Dist.Integrity, files: map[string][]byte{}}
	tr := tar.NewReader(zr)
	for {
		h, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			log.Fatal(err)
		}
		if h.Typeflag != tar.TypeReg {
			continue
		}
		b, err := io.ReadAll(tr)
		if err != nil {
			log.Fatal(err)
		}
		p.files[strings.TrimPrefix(h.Name, "package/")] = b
	}
	return p
}

func sri(b []byte) string {
	sum := sha512.Sum384(b)
	return "sha384-" + base64.StdEncoding.EncodeToString(sum[:])
}
