package basicauth

import (
	"crypto/pbkdf2"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/hex"
	"strconv"
	"strings"
)

// PBKDF2Iterations is the PBKDF2-HMAC-SHA256 iteration count used by
// [HashPasswordPBKDF2]. 600,000 is the OWASP (2023+) recommendation for
// PBKDF2-HMAC-SHA256 credential storage.
const PBKDF2Iterations = 600_000

const (
	// pbkdf2Tag is the algorithm tag that opens every HashPasswordPBKDF2
	// string; VerifyPassword dispatches on it.
	pbkdf2Tag = "pbkdf2-sha256"
	// pbkdf2SaltLen is the salt length in bytes generated by HashPasswordPBKDF2.
	pbkdf2SaltLen = 16
	// pbkdf2KeyLen is the derived-key length in bytes; fixed at the SHA-256
	// digest size so a truncated (weaker) stored hash is rejected outright.
	pbkdf2KeyLen = sha256.Size
)

// HashPasswordPBKDF2 derives a salted, slow credential hash of password
// suitable for storing in [Config].HashedUsers.
//
// The output is PBKDF2-HMAC-SHA256 over a fresh 16-byte crypto/rand salt
// with [PBKDF2Iterations] iterations and a 32-byte derived key, encoded as
//
//	pbkdf2-sha256$<iterations>$<salt-base64>$<hash-base64>
//
// (standard, padded base64). Every call produces a different string for the
// same password because the salt is random; compare with [VerifyPassword],
// never with ==. The function panics only if crypto/rand fails, which is
// treated as unrecoverable (as in the rest of this package).
//
// As with every PBKDF2 implementation, the password is the HMAC key, so a
// password shorter than the SHA-256 block size is equivalent to itself with
// trailing NUL bytes appended. RFC 7617 restricts Basic passwords to TEXT
// (no control characters), so this has no practical effect here.
func HashPasswordPBKDF2(password string) string {
	salt := make([]byte, pbkdf2SaltLen)
	if _, err := rand.Read(salt); err != nil {
		panic("basicauth: crypto/rand failed: " + err.Error())
	}
	key, err := pbkdf2.Key(sha256.New, password, salt, PBKDF2Iterations, pbkdf2KeyLen)
	if err != nil {
		// Only reachable under FIPS-140 mode with parameters below the
		// module's floor; ours are well above it.
		panic("basicauth: pbkdf2: " + err.Error())
	}
	return pbkdf2Tag + "$" + strconv.Itoa(PBKDF2Iterations) + "$" +
		base64.StdEncoding.EncodeToString(salt) + "$" +
		base64.StdEncoding.EncodeToString(key)
}

// VerifyPassword reports whether password matches the stored hash. It is
// a ready-made [Config].HashedUsersFunc that understands both hash formats
// this package has ever produced:
//
//   - pbkdf2-sha256$<iter>$<salt>$<hash> from [HashPasswordPBKDF2]
//     (preferred);
//   - a bare hex SHA-256 digest from the deprecated [HashPassword], kept so
//     existing deployments keep authenticating while they migrate.
//
// The comparison uses [subtle.ConstantTimeCompare]. A malformed hash still
// performs a derivation before returning false, so the format-error branch
// is not distinguishable by timing from a wrong password. Per-request cost
// is one PBKDF2 derivation (hundreds of milliseconds at 600k iterations),
// which is the point: cache authenticated sessions upstream if the
// endpoint is hot.
func VerifyPassword(hash, password string) bool {
	if isPBKDF2Hash(hash) {
		return verifyPBKDF2(hash, password)
	}
	return verifyLegacySHA256(hash, password)
}

// isPBKDF2Hash reports whether hash carries the HashPasswordPBKDF2 tag.
func isPBKDF2Hash(hash string) bool {
	return strings.HasPrefix(hash, pbkdf2Tag+"$")
}

// verifyPBKDF2 parses a pbkdf2-sha256$<iter>$<salt>$<hash> string and
// checks password against it in constant time.
func verifyPBKDF2(hash, password string) bool {
	iter, salt, want, ok := parsePBKDF2(hash)
	if !ok {
		// Burn the same work a well-formed hash would, then fail.
		var dummySalt [pbkdf2SaltLen]byte
		var dummy [pbkdf2KeyLen]byte
		got, _ := pbkdf2.Key(sha256.New, password, dummySalt[:], PBKDF2Iterations, pbkdf2KeyLen)
		_ = subtle.ConstantTimeCompare(got, dummy[:])
		return false
	}
	got, err := pbkdf2.Key(sha256.New, password, salt, iter, pbkdf2KeyLen)
	if err != nil {
		return false
	}
	return subtle.ConstantTimeCompare(got, want) == 1
}

// parsePBKDF2 splits and decodes a HashPasswordPBKDF2 string. It rejects
// anything that is not exactly four fields, a positive decimal iteration
// count, a non-empty base64 salt, and a base64 hash of exactly
// pbkdf2KeyLen bytes.
func parsePBKDF2(hash string) (iter int, salt, key []byte, ok bool) {
	parts := strings.Split(hash, "$")
	if len(parts) != 4 || parts[0] != pbkdf2Tag {
		return 0, nil, nil, false
	}
	// ParseUint (not Atoi) refuses signs and is bounded to 31 bits so a
	// hostile iteration count can neither go negative nor overflow int
	// on 32-bit targets.
	n, err := strconv.ParseUint(parts[1], 10, 31)
	if err != nil || n == 0 {
		return 0, nil, nil, false
	}
	salt, err = base64.StdEncoding.DecodeString(parts[2])
	if err != nil || len(salt) == 0 {
		return 0, nil, nil, false
	}
	key, err = base64.StdEncoding.DecodeString(parts[3])
	if err != nil || len(key) != pbkdf2KeyLen {
		return 0, nil, nil, false
	}
	return int(n), salt, key, true
}

// verifyLegacySHA256 checks password against a bare hex SHA-256 digest as
// produced by the deprecated HashPassword. Constant-time per the
// HashedUsersFunc contract, including on malformed input.
func verifyLegacySHA256(hash, password string) bool {
	want, err := hex.DecodeString(hash)
	got := sha256.Sum256([]byte(password))
	if err != nil || len(want) != sha256.Size {
		var dummy [sha256.Size]byte
		_ = subtle.ConstantTimeCompare(got[:], dummy[:])
		return false
	}
	return subtle.ConstantTimeCompare(got[:], want) == 1
}

// allPBKDF2 reports whether every stored hash carries the pbkdf2-sha256
// tag — the only shape for which applyDefaults may wire VerifyPassword in
// without an explicit HashedUsersFunc.
func allPBKDF2(hashes map[string]string) bool {
	for _, h := range hashes {
		if !isPBKDF2Hash(h) {
			return false
		}
	}
	return true
}
