package basicauth

import (
	"crypto/pbkdf2"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/hex"
	"strconv"
	"strings"
)

// PBKDF2Iterations is the PBKDF2-HMAC-SHA256 iteration count used by
// [HashPasswordPBKDF2]. 600,000 is the OWASP (2023+) recommendation for
// PBKDF2-HMAC-SHA256 credential storage.
const PBKDF2Iterations = 600_000

const (
	// pbkdf2Tag is the algorithm tag that opens every HashPasswordPBKDF2
	// string; VerifyPassword dispatches on it.
	pbkdf2Tag = "pbkdf2-sha256"
	// pbkdf2SaltLen is the salt length in bytes generated by HashPasswordPBKDF2.
	pbkdf2SaltLen = 16
	// pbkdf2KeyLen is the derived-key length in bytes; fixed at the SHA-256
	// digest size so a truncated (weaker) stored hash is rejected outright.
	pbkdf2KeyLen = sha256.Size

	// VerifyPassword honours the parameters carried by a stored hash only
	// inside the window below. HashPasswordPBKDF2 itself always emits
	// PBKDF2Iterations and pbkdf2SaltLen; the window exists to bound what
	// a hostile or mistyped stored value can make the verifier do — a
	// stored hash reaches the verifier on every request for that user and,
	// through applyDefaults' dummy hash, on every request for an unknown
	// user too — while leaving headroom for hashes produced elsewhere at a
	// higher cost.
	//
	// minPBKDF2Iterations refuses downgrades: an entry below the count this
	// package emits would verify at a fraction of the intended cost, which
	// is exactly the fast-hash storage the package refuses to default to.
	// It is a literal, not an alias of PBKDF2Iterations: if the default is
	// ever raised, this stays at the lowest count ever emitted so hashes
	// already sitting in stores keep verifying.
	minPBKDF2Iterations = 600_000
	// maxPBKDF2Iterations caps the CPU one verification can burn. Cost is
	// linear in the count (~0.2 s at the default, ~3 s at this cap on a
	// 2026 laptop); the 31-bit count the parser used to accept would have
	// cost ~10 minutes per request.
	maxPBKDF2Iterations = 10_000_000
	// minPBKDF2SaltLen refuses salts shorter than the 128 bits this package
	// emits (NIST SP 800-132 §5.1). Same rule as the iteration floor: a
	// literal pinned at the shortest salt ever emitted.
	minPBKDF2SaltLen = 16
)

// Compile-time guard: HashPasswordPBKDF2's own parameters must sit inside
// the window VerifyPassword enforces, or the default wiring would reject
// every hash it produces. A negative untyped constant does not convert to
// uint, so a bad edit fails to build.
const (
	_ = uint(PBKDF2Iterations - minPBKDF2Iterations)
	_ = uint(maxPBKDF2Iterations - PBKDF2Iterations)
	_ = uint(pbkdf2SaltLen - minPBKDF2SaltLen)
)

// HashPasswordPBKDF2 derives a salted, slow credential hash of password
// suitable for storing in [Config].HashedUsers.
//
// The output is PBKDF2-HMAC-SHA256 over a fresh 16-byte crypto/rand salt
// with [PBKDF2Iterations] iterations and a 32-byte derived key, encoded as
//
//	pbkdf2-sha256$<iterations>$<salt-base64>$<hash-base64>
//
// (standard, padded base64). Every call produces a different string for the
// same password because the salt is random; compare with [VerifyPassword],
// never with ==. The function panics only if crypto/rand fails, which is
// treated as unrecoverable (as in the rest of this package).
//
// As with every PBKDF2 implementation, the password is the HMAC key, so a
// password shorter than the SHA-256 block size is equivalent to itself with
// trailing NUL bytes appended. RFC 7617 restricts Basic passwords to TEXT
// (no control characters), so this has no practical effect here.
func HashPasswordPBKDF2(password string) string {
	salt := make([]byte, pbkdf2SaltLen)
	if _, err := rand.Read(salt); err != nil {
		panic("basicauth: crypto/rand failed: " + err.Error())
	}
	key, err := pbkdf2.Key(sha256.New, password, salt, PBKDF2Iterations, pbkdf2KeyLen)
	if err != nil {
		// Only reachable under FIPS-140 mode with parameters below the
		// module's floor; ours are well above it.
		panic("basicauth: pbkdf2: " + err.Error())
	}
	return pbkdf2Tag + "$" + strconv.Itoa(PBKDF2Iterations) + "$" +
		base64.StdEncoding.EncodeToString(salt) + "$" +
		base64.StdEncoding.EncodeToString(key)
}

// VerifyPassword reports whether password matches the stored hash. It is
// a ready-made [Config].HashedUsersFunc that understands both hash formats
// this package has ever produced:
//
//   - pbkdf2-sha256$<iter>$<salt>$<hash> from [HashPasswordPBKDF2]
//     (preferred). The stored parameters are honoured only within a fixed
//     window — 600,000 ≤ iterations ≤ 10,000,000, salt of at least 16
//     bytes, key of exactly 32 bytes — so a stored value can neither
//     downgrade the derivation below the cost this package emits nor make
//     it cost minutes of CPU. Anything outside the window fails, after the
//     same work as below;
//   - a bare hex SHA-256 digest from the deprecated [HashPassword], kept so
//     existing deployments keep authenticating while they migrate.
//
// Timing: every call performs exactly one PBKDF2 derivation — at the
// stored iteration count for a well-formed pbkdf2-sha256 hash, and at
// [PBKDF2Iterations] for everything else (a legacy digest, a malformed or
// out-of-window string, or "" as callers pass for unknown users) — followed
// by a [subtle.ConstantTimeCompare]. The format of the stored hash is
// therefore not recoverable from response time, which is what the
// HashedUsersFunc contract asks for. What does remain observable is a
// non-default iteration count in a pbkdf2-sha256 entry, exactly as
// bcrypt's cost factor is; the microsecond-scale parsing that differs
// between the two formats is lost in the hundreds of milliseconds of
// derivation.
//
// That derivation is the per-request cost for every entry, legacy digests
// included — which is the point: cache authenticated sessions upstream if
// the endpoint is hot.
func VerifyPassword(hash, password string) bool {
	if isPBKDF2Hash(hash) {
		return verifyPBKDF2(hash, password)
	}
	return verifyLegacySHA256(hash, password)
}

// isPBKDF2Hash reports whether hash carries the HashPasswordPBKDF2 tag.
func isPBKDF2Hash(hash string) bool {
	return strings.HasPrefix(hash, pbkdf2Tag+"$")
}

// verifyPBKDF2 parses a pbkdf2-sha256$<iter>$<salt>$<hash> string and
// checks password against it in constant time.
func verifyPBKDF2(hash, password string) bool {
	iter, salt, want, ok := parsePBKDF2(hash)
	if !ok {
		burnPBKDF2(password)
		return false
	}
	got, err := pbkdf2.Key(sha256.New, password, salt, iter, pbkdf2KeyLen)
	if err != nil {
		return false
	}
	return subtle.ConstantTimeCompare(got, want) == 1
}

// burnPBKDF2 derives a key from password at the default cost and discards
// it. Every VerifyPassword path that does not derive against a stored
// pbkdf2-sha256 hash calls this instead, so the verifier costs one
// derivation whatever the stored value looks like.
func burnPBKDF2(password string) {
	var dummySalt [pbkdf2SaltLen]byte
	var dummy [pbkdf2KeyLen]byte
	got, _ := pbkdf2.Key(sha256.New, password, dummySalt[:], PBKDF2Iterations, pbkdf2KeyLen)
	_ = subtle.ConstantTimeCompare(got, dummy[:])
}

// parsePBKDF2 splits and decodes a HashPasswordPBKDF2 string. It rejects
// anything that is not exactly four fields, a decimal iteration count in
// [minPBKDF2Iterations, maxPBKDF2Iterations], a base64 salt of at least
// minPBKDF2SaltLen bytes, and a base64 hash of exactly pbkdf2KeyLen bytes.
func parsePBKDF2(hash string) (iter int, salt, key []byte, ok bool) {
	parts := strings.Split(hash, "$")
	if len(parts) != 4 || parts[0] != pbkdf2Tag {
		return 0, nil, nil, false
	}
	// ParseUint (not Atoi) refuses signs; the window check is the real
	// bound, and keeps int(n) safe on 32-bit targets as a side effect.
	n, err := strconv.ParseUint(parts[1], 10, 32)
	if err != nil || n < minPBKDF2Iterations || n > maxPBKDF2Iterations {
		return 0, nil, nil, false
	}
	salt, err = base64.StdEncoding.DecodeString(parts[2])
	if err != nil || len(salt) < minPBKDF2SaltLen {
		return 0, nil, nil, false
	}
	key, err = base64.StdEncoding.DecodeString(parts[3])
	if err != nil || len(key) != pbkdf2KeyLen {
		return 0, nil, nil, false
	}
	return int(n), salt, key, true
}

// verifyLegacySHA256 checks password against a bare hex SHA-256 digest as
// produced by the deprecated HashPassword. It burns one default-cost PBKDF2
// derivation first — on the valid-hex and the malformed path alike, ""
// included — so a legacy entry, an unknown user and a pbkdf2-sha256 entry
// all cost the same. The candidate digest comes from HashPassword itself,
// the one deliberately retained (deprecated, CodeQL-tracked) fast-hash
// site, rather than a second inline SHA-256 over the password; the stored
// hex is re-encoded so both sides are 64-byte lower-case strings for the
// constant-time compare.
func verifyLegacySHA256(hash, password string) bool {
	burnPBKDF2(password)
	want, err := hex.DecodeString(hash)
	malformed := err != nil || len(want) != sha256.Size
	if malformed {
		want = make([]byte, sha256.Size)
	}
	match := subtle.ConstantTimeCompare(
		[]byte(HashPassword(password)), []byte(hex.EncodeToString(want))) == 1
	return match && !malformed
}

// allPBKDF2 reports whether every stored hash carries the pbkdf2-sha256
// tag — the only shape for which applyDefaults may wire VerifyPassword in
// without an explicit HashedUsersFunc.
func allPBKDF2(hashes map[string]string) bool {
	for _, h := range hashes {
		if !isPBKDF2Hash(h) {
			return false
		}
	}
	return true
}

// malformedPBKDF2Entry returns the username of a stored hash that carries
// the pbkdf2-sha256 tag but does not parse within the accepted window
// (bad=true), or bad=false when every entry parses. applyDefaults uses it
// to turn a mistyped iteration count or salt in an auto-wired store into a
// startup panic that names the entry, instead of a 401 on every request
// for that user.
func malformedPBKDF2Entry(hashes map[string]string) (user string, bad bool) {
	for u, h := range hashes {
		if _, _, _, ok := parsePBKDF2(h); !ok {
			return u, true
		}
	}
	return "", false
}
