// Code generated by assets/update.go; DO NOT EDIT.

package swagger

// The exact upstream versions this release is pinned to. Swagger UI is
// embedded at SwaggerUIVersion and served by default; with Config.CDN the
// pages load each renderer from jsDelivr at these versions.
const (
	// SwaggerUIVersion is the embedded and CDN swagger-ui-dist version.
	SwaggerUIVersion = "5.33.1"
	// ScalarVersion is the CDN @scalar/api-reference version.
	ScalarVersion = "1.72.4"
	// ReDocVersion is the CDN redoc version.
	ReDocVersion = "2.5.4"
)

// Subresource Integrity values (sha384) of the files the pages load.
// Sources (npm tarball, registry integrity):
//
//	https://registry.npmjs.org/swagger-ui-dist/-/swagger-ui-dist-5.33.1.tgz sha512-H872wWkA53bFIsGgi7OWgmq+CRWw3nFQGdJWRqOB9wNwTm6e5ol34+qPDkV4AJlK+gglM2EsJiOOzsGsEGbluA==
//	https://registry.npmjs.org/@scalar/api-reference/-/api-reference-1.72.4.tgz sha512-HKsUqCJbXhmz/5j6ETceXVgnlZKOX1uidF7jz8elSuzKE6FJjJYhK1G7WqxHk4zLabbSb13QHQ9yKUikf8XLBQ==
//	https://registry.npmjs.org/redoc/-/redoc-2.5.4.tgz sha512-M6jWhG1qoBnH6TFmzJnstyCZ87HmOY/UzDm78mHiYihEdlV/YcS9ogOo1NlElnJMeLsyxHFe2yFc4sNjHTrABQ==
const (
	sriSwaggerUICSS    = "sha384-Ov4/wv3j2bmct8cDc5X4ngJZohVPzEmc6uDPH8WeljUxO5vtoykvMEfbu9Vh6RaW"
	sriSwaggerUIBundle = "sha384-ZPehFMQommnnuaZ4rpxgkgTT2DKFVp4hZC/7pLit+9Lek9T1YGSo23eHFbvNkXkw"
	sriSwaggerUIPreset = "sha384-My2aDM4r2Mbm3ybHcubKm9O9U8FEjvF/O5nGvE9YK5dzqOTbWEKa79RPJ1krdMaF"
	sriScalar          = "sha384-omTRdD9MbjA1vm12DqRUVvqJlr3VzSixvAdF1Jruu9AJOiJKyTKraIB6DyX+m10M"
	sriReDoc           = "sha384-w447zOpYfw/1Tv/5AK9NfHTlQIqE3RVR6KY62jCyy9zNDgO64cMwGGP1Fj0zJVf5"
)
